# Base URL for the Task API
@baseUrl = http://localhost:6003/api/tasks
@taskId = 675c84109d5b73d35cdc14b6  
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzVjNmIwZmRmYTY2OWI5MjA4ODE3MWEiLCJpYXQiOjE3MzQxMDk5NjcsImV4cCI6MTczNDExNzE2N30.8iB4dijpBNuBSt8-qE3Dl0cMfnpa0XDUTtGIry9A0kY

### Fetch All Tasks
GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a New Task
POST {{baseUrl}}/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Tassk",
  "start_time": "1702483200", 
  "end_time": "1702486800",  
  "priority": "2"
}

### Update an Existing Task
PUT {{baseUrl}}/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Updated Task 1",
  "status": "finished",
  "priority":"2"
}

### Update Task Status
PATCH {{baseUrl}}/update-status/{{taskId}}
Content-Type: application/json

{
  "status": "finished",
  "updated_by": "user2",
  "priority":"2"
}

### Get Task by ID
GET {{baseUrl}}/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete a Task
DELETE {{baseUrl}}/delete/{{taskId}}
Content-Type: application/json



####
GET {{baseUrl}}/stats
Content-Type: application/json
Authorization: Bearer {{token}}